export const Colors = {
  light: {
    text: '#333',
    textSecondary: '#666',
    background: '#f5f5f5',
    card: '#fff',
    border: '#ddd',
    primary: '#007AFF',
    error: '#c33',
    errorBg: '#fee',
    errorBorder: '#fcc',
    hint: '#999',
    tabInactive: '#999',
    avatar: '#007AFF',
    logoutBorder: '#c33',
  },
  dark: {
    text: '#fff',
    textSecondary: '#aaa',
    background: '#000',
    card: '#1c1c1e',
    border: '#38383a',
    primary: '#0a84ff',
    error: '#ff453a',
    errorBg: '#2c1517',
    errorBorder: '#4a1f22',
    hint: '#666',
    tabInactive: '#666',
    avatar: '#0a84ff',
    logoutBorder: '#ff453a',
  },
};